"""
Per-repo .offload/ directory abstraction.

Each repo on the dev machine that wants to be managed by Offload gets a
`.offload/` directory at its root. This module is the single read/write
interface for that directory.

Layout (see README.md and the templates/repo-init/ folder):

    <repo>/.offload/
    ├── init/                  # onboarding template (copied from server templates)
    ├── context/               # long-term context (generated by Claude during init)
    │   ├── summary.md
    │   ├── architecture.md
    │   ├── conventions.md
    │   └── glossary.md
    ├── topics/                # work items
    └── state.json             # repo-level metadata
"""
from __future__ import annotations

import json
import shutil
import subprocess
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional


# Server-side template directory (copied into <repo>/.offload/init/ on init)
TEMPLATE_DIR = Path(__file__).parent / "templates" / "repo-init"

CONTEXT_FILES = ["summary.md", "architecture.md", "conventions.md", "glossary.md"]

# Init status values
STATUS_NOT_INITIALIZED = "not_initialized"
STATUS_INITIALIZING = "initializing"
STATUS_READY = "ready"
STATUS_FAILED = "failed"

# Maximum length of the summary excerpt shown on iOS cards
SUMMARY_EXCERPT_MAX = 300

# Claude CLI timeout for init runs (seconds)
INIT_TIMEOUT = 600


@dataclass
class RepoOffload:
    """Wraps a repo path and provides read/write access to its .offload/ directory."""

    repo_path: Path

    @property
    def offload_dir(self) -> Path:
        return self.repo_path / ".offload"

    @property
    def init_dir(self) -> Path:
        return self.offload_dir / "init"

    @property
    def context_dir(self) -> Path:
        return self.offload_dir / "context"

    @property
    def topics_dir(self) -> Path:
        return self.offload_dir / "topics"

    @property
    def state_path(self) -> Path:
        return self.offload_dir / "state.json"

    @property
    def summary_path(self) -> Path:
        return self.context_dir / "summary.md"

    # ---- Status / introspection ------------------------------------------------

    def is_initialized(self) -> bool:
        """A repo is 'initialized' if at least summary.md exists with content."""
        if not self.summary_path.is_file():
            return False
        try:
            return self.summary_path.stat().st_size > 0
        except OSError:
            return False

    def read_state(self) -> Dict[str, Any]:
        if not self.state_path.is_file():
            return {}
        try:
            return json.loads(self.state_path.read_text())
        except (OSError, json.JSONDecodeError):
            return {}

    def write_state(self, state: Dict[str, Any]) -> None:
        self.offload_dir.mkdir(parents=True, exist_ok=True)
        self.state_path.write_text(json.dumps(state, indent=2))

    def update_state(self, **fields: Any) -> Dict[str, Any]:
        state = self.read_state()
        state.update(fields)
        self.write_state(state)
        return state

    def read_summary_excerpt(self) -> Optional[str]:
        """Return the first paragraph of summary.md (skipping the heading), trimmed."""
        if not self.summary_path.is_file():
            return None
        try:
            content = self.summary_path.read_text()
        except OSError:
            return None
        lines = content.splitlines()
        # Find first non-empty, non-heading, non-comment line, then accumulate until blank
        paragraph: list[str] = []
        in_paragraph = False
        for line in lines:
            stripped = line.strip()
            if not in_paragraph:
                if not stripped:
                    continue
                if stripped.startswith("#"):
                    continue
                if stripped.startswith("<!--"):
                    continue
                in_paragraph = True
                paragraph.append(stripped)
            else:
                if not stripped:
                    break
                paragraph.append(stripped)
        if not paragraph:
            return None
        text = " ".join(paragraph)
        if len(text) > SUMMARY_EXCERPT_MAX:
            text = text[: SUMMARY_EXCERPT_MAX - 1].rstrip() + "…"
        return text

    def read_context(self) -> Dict[str, str]:
        """Return all context/*.md files as {filename: content}."""
        result: Dict[str, str] = {}
        if not self.context_dir.is_dir():
            return result
        for name in CONTEXT_FILES:
            path = self.context_dir / name
            if path.is_file():
                try:
                    result[name] = path.read_text()
                except OSError:
                    pass
        return result

    # ---- Initialization --------------------------------------------------------

    def stage_init_template(self) -> None:
        """Copy the server's init template into <repo>/.offload/init/."""
        self.offload_dir.mkdir(parents=True, exist_ok=True)
        # Wipe and recopy to make re-init clean
        if self.init_dir.exists():
            shutil.rmtree(self.init_dir)
        shutil.copytree(TEMPLATE_DIR, self.init_dir)
        self.context_dir.mkdir(parents=True, exist_ok=True)
        self.topics_dir.mkdir(parents=True, exist_ok=True)

    def ensure_gitignore(self) -> None:
        """Add .offload/ to the repo's .gitignore if not already present."""
        gitignore = self.repo_path / ".gitignore"
        marker = ".offload/"
        existing = ""
        if gitignore.is_file():
            try:
                existing = gitignore.read_text()
            except OSError:
                return
        # Check if marker is already there (allow leading slash, comments, etc.)
        for line in existing.splitlines():
            stripped = line.strip()
            if stripped == ".offload/" or stripped == "/.offload/" or stripped == ".offload":
                return
        # Append
        try:
            with gitignore.open("a") as f:
                if existing and not existing.endswith("\n"):
                    f.write("\n")
                f.write("\n# Offload (https://github.com/anthropics/offload)\n")
                f.write(".offload/\n")
        except OSError:
            pass

    # ---- Source isolation helpers ------------------------------------------------

    def _git_dirty_files(self) -> set:
        """Return set of tracked files with uncommitted changes (relative paths)."""
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "HEAD"],
                cwd=self.repo_path, capture_output=True, text=True, timeout=10,
            )
            staged = subprocess.run(
                ["git", "diff", "--name-only", "--cached"],
                cwd=self.repo_path, capture_output=True, text=True, timeout=10,
            )
            files = set()
            for line in (result.stdout + staged.stdout).splitlines():
                stripped = line.strip()
                if stripped:
                    files.add(stripped)
            return files
        except Exception:
            return set()

    def _revert_source_changes(self, pre_dirty: set) -> List[str]:
        """
        After init, revert any tracked file changes that weren't dirty before.
        Returns list of reverted file paths (relative).
        .offload/ is gitignored so it's never affected.
        """
        post_dirty = self._git_dirty_files()
        new_changes = post_dirty - pre_dirty
        if not new_changes:
            return []
        reverted: List[str] = []
        for filepath in sorted(new_changes):
            # Safety: never revert .offload/ (shouldn't be tracked, but just in case)
            if filepath.startswith(".offload"):
                continue
            try:
                subprocess.run(
                    ["git", "checkout", "--", filepath],
                    cwd=self.repo_path, capture_output=True, timeout=10,
                )
                reverted.append(filepath)
            except Exception:
                pass
        # Also discard any untracked files Claude may have created outside .offload/
        try:
            untracked = subprocess.run(
                ["git", "ls-files", "--others", "--exclude-standard"],
                cwd=self.repo_path, capture_output=True, text=True, timeout=10,
            )
            for line in untracked.stdout.splitlines():
                filepath = line.strip()
                if filepath and not filepath.startswith(".offload"):
                    full = self.repo_path / filepath
                    if full.is_file():
                        full.unlink()
                        reverted.append(f"{filepath} (new, deleted)")
        except Exception:
            pass
        return reverted

    def uninstall(self, remove_gitignore_entry: bool = True) -> None:
        """
        Remove the .offload/ directory and optionally clean up .gitignore.
        Raises OSError if the directory could not be fully removed.
        """
        if self.offload_dir.exists():
            shutil.rmtree(self.offload_dir)
            # Verify it's actually gone.
            if self.offload_dir.exists():
                raise OSError(f"Failed to remove {self.offload_dir}: directory still exists after rmtree.")
        if remove_gitignore_entry:
            self._remove_gitignore_entry()

    def _remove_gitignore_entry(self) -> None:
        gitignore = self.repo_path / ".gitignore"
        if not gitignore.is_file():
            return
        try:
            lines = gitignore.read_text().splitlines(keepends=True)
        except OSError:
            return
        offload_markers = {".offload/", "/.offload/", ".offload"}
        offload_comment = "# Offload (https://github.com/anthropics/offload)"
        out: List[str] = []
        skip_next_blank = False
        for line in lines:
            stripped = line.strip()
            if stripped in offload_markers:
                skip_next_blank = True
                continue
            # Also remove the comment header we inserted
            if stripped == offload_comment:
                skip_next_blank = True
                continue
            if skip_next_blank and not stripped:
                skip_next_blank = False
                continue
            skip_next_blank = False
            out.append(line)
        try:
            gitignore.write_text("".join(out))
        except OSError:
            pass

    def run_claude_init(
        self,
        log_callback: Optional[Callable[[str], None]] = None,
        register_proc: Optional[Callable[[subprocess.Popen], None]] = None,
    ) -> "InitResult":
        """
        Run claude in the repo with INIT_PROMPT.md as the prompt.
        Streams progress via stream-json output format; log_callback is invoked
        per parsed event with a human-readable line.
        register_proc is called with the Popen object so callers can cancel it.
        """
        prompt_path = self.init_dir / "INIT_PROMPT.md"
        if not prompt_path.is_file():
            return InitResult(success=False, error="INIT_PROMPT.md missing in .offload/init/")

        try:
            prompt = prompt_path.read_text()
        except OSError as e:
            return InitResult(success=False, error=f"Failed to read INIT_PROMPT.md: {e}")

        def log(msg: str) -> None:
            if log_callback:
                log_callback(msg)

        log("Starting Claude agent…")

        # Record source state before Claude runs (for isolation enforcement)
        pre_diff = self._git_dirty_files()

        try:
            proc = subprocess.Popen(
                [
                    "claude", "-p", prompt,
                    "--output-format", "stream-json",
                    "--verbose",
                    "--dangerously-skip-permissions",
                ],
                cwd=self.repo_path,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                bufsize=1,
            )
        except FileNotFoundError:
            return InitResult(
                success=False,
                error="Claude CLI not found. Install with: npm install -g @anthropic-ai/claude-code",
            )

        if register_proc:
            register_proc(proc)

        stdout_lines: List[str] = []
        assert proc.stdout is not None
        try:
            for raw_line in proc.stdout:
                line = raw_line.rstrip("\n")
                stdout_lines.append(line)
                for human in _format_stream_event(line):
                    log(human)
        except Exception as e:  # noqa: BLE001
            log(f"Stream read error: {e}")

        try:
            proc.wait(timeout=INIT_TIMEOUT)
        except subprocess.TimeoutExpired:
            proc.kill()
            return InitResult(success=False, error=f"Claude init timed out after {INIT_TIMEOUT}s")

        stderr_text = ""
        if proc.stderr:
            try:
                stderr_text = proc.stderr.read() or ""
            except Exception:
                pass

        full_stdout = "\n".join(stdout_lines)

        if proc.returncode != 0:
            # Produce a clean human-readable error, not raw JSON dumps
            if proc.returncode == -9:
                clean_error = "Process was killed (likely cancelled)."
            elif proc.returncode == -15:
                clean_error = "Process was terminated."
            else:
                # Try to extract something useful; fall back to exit code
                for line in reversed(stderr_text.splitlines()):
                    stripped = line.strip()
                    if stripped and not stripped.startswith("{"):
                        clean_error = f"Claude exited with status {proc.returncode}: {stripped[:200]}"
                        break
                else:
                    clean_error = f"Claude exited with status {proc.returncode}."
            return InitResult(
                success=False,
                error=clean_error,
                stdout=full_stdout,
                stderr=stderr_text,
            )

        # === ISOLATION ENFORCEMENT ===
        # Offload is an observer — init must never modify source code.
        # Revert any tracked file changes Claude made outside .offload/.
        reverted = self._revert_source_changes(pre_diff)
        if reverted:
            log(f"🛡️ Reverted {len(reverted)} source file(s) touched by init agent")
            for f in reverted[:10]:
                log(f"   ↩ {f}")

        if not self.is_initialized():
            return InitResult(
                success=False,
                error="Claude finished but summary.md was not created with content.",
                stdout=full_stdout,
                stderr=stderr_text,
            )

        log("✅ Initialization complete")
        return InitResult(success=True, stdout=full_stdout, stderr=stderr_text)


@dataclass
class InitResult:
    success: bool
    error: Optional[str] = None
    stdout: str = ""
    stderr: str = ""


@dataclass
class _InitJob:
    project_path: str
    status: str
    started_at: str
    finished_at: Optional[str] = None
    error: Optional[str] = None
    log: List[str] = field(default_factory=list)


MAX_LOG_LINES = 200


def _format_stream_event(raw_line: str) -> List[str]:
    """Parse one line of claude's stream-json output and return human-readable strings."""
    raw_line = raw_line.strip()
    if not raw_line:
        return []
    try:
        obj = json.loads(raw_line)
    except json.JSONDecodeError:
        return [raw_line[:300]] if len(raw_line) > 0 else []

    event_type = obj.get("type", "")
    if event_type == "system":
        subtype = obj.get("subtype", "")
        if subtype == "init":
            return ["🚀 Claude session initialized"]
        return []

    if event_type == "assistant":
        message = obj.get("message", {})
        content = message.get("content", [])
        parts: List[str] = []
        if not isinstance(content, list):
            return []
        for item in content:
            if not isinstance(item, dict):
                continue
            item_type = item.get("type")
            if item_type == "text":
                text = (item.get("text") or "").strip()
                if text:
                    # Limit long thinking blocks
                    parts.append(text if len(text) <= 240 else text[:237] + "…")
            elif item_type == "tool_use":
                tool = item.get("name", "tool")
                inp = item.get("input") or {}
                if tool == "Read":
                    fp = inp.get("file_path", "")
                    parts.append(f"📖 Read {_short_path(fp)}")
                elif tool == "Write":
                    fp = inp.get("file_path", "")
                    parts.append(f"✏️ Write {_short_path(fp)}")
                elif tool == "Edit":
                    fp = inp.get("file_path", "")
                    parts.append(f"✏️ Edit {_short_path(fp)}")
                elif tool == "Bash":
                    cmd = (inp.get("command") or "")[:100]
                    parts.append(f"⚙️ Run {cmd}")
                elif tool == "Glob":
                    parts.append(f"🔍 Glob {inp.get('pattern', '')}")
                elif tool == "Grep":
                    parts.append(f"🔍 Grep {inp.get('pattern', '')}")
                elif tool == "LS":
                    parts.append(f"📂 List {_short_path(inp.get('path', ''))}")
                else:
                    parts.append(f"🔧 {tool}")
        return parts

    if event_type == "user":
        # Tool results — usually noisy, skip unless it's an error
        message = obj.get("message", {})
        content = message.get("content", [])
        if isinstance(content, list):
            for item in content:
                if isinstance(item, dict) and item.get("is_error"):
                    txt = str(item.get("content", ""))[:200]
                    return [f"⚠️ {txt}"]
        return []

    if event_type == "result":
        if obj.get("is_error"):
            return [f"❌ {str(obj.get('result', ''))[:300]}"]
        return []  # success is announced by the caller

    return []


def _short_path(path: str) -> str:
    """Trim absolute paths to show just the last 2-3 components."""
    if not path:
        return ""
    parts = path.split("/")
    if len(parts) > 3:
        return ".../" + "/".join(parts[-3:])
    return path


class InitRunner:
    """
    Tracks per-repo init state in memory. Spawns background threads for actual
    Claude runs so HTTP requests return immediately.
    Publishes real-time log events through an optional event_bus.
    """

    def __init__(self, event_bus: Any = None) -> None:
        self._jobs: Dict[str, _InitJob] = {}
        self._lock = threading.RLock()
        self._event_bus = event_bus
        self._procs: Dict[str, subprocess.Popen] = {}  # for cancel support

    def status(self, project_path: str) -> str:
        """Return the current status string for a project."""
        with self._lock:
            job = self._jobs.get(project_path)
            if job:
                return job.status
        # Fall back to filesystem check
        repo = RepoOffload(Path(project_path))
        if repo.is_initialized():
            return STATUS_READY
        return STATUS_NOT_INITIALIZED

    def is_running(self, project_path: str) -> bool:
        with self._lock:
            job = self._jobs.get(project_path)
            return job is not None and job.status == STATUS_INITIALIZING

    def get_job(self, project_path: str) -> Optional[_InitJob]:
        with self._lock:
            return self._jobs.get(project_path)

    def get_log(self, project_path: str) -> List[str]:
        with self._lock:
            job = self._jobs.get(project_path)
            if not job:
                return []
            return list(job.log)

    def forget(self, project_path: str) -> None:
        """Drop any in-memory state for this project (used after uninstall)."""
        with self._lock:
            self._jobs.pop(project_path, None)
            self._procs.pop(project_path, None)

    def cancel(self, project_path: str) -> bool:
        """Kill a running init process. Returns True if there was something to cancel."""
        with self._lock:
            proc = self._procs.get(project_path)
            job = self._jobs.get(project_path)
            if proc is None or job is None or job.status != STATUS_INITIALIZING:
                return False
        proc.kill()
        try:
            proc.wait(timeout=5)
        except Exception:
            pass
        # Clean up partially-written .offload/ so state is pristine
        repo = RepoOffload(Path(project_path))
        if repo.offload_dir.exists():
            shutil.rmtree(repo.offload_dir, ignore_errors=True)
        with self._lock:
            job = self._jobs.get(project_path)
            if job:
                job.status = STATUS_FAILED
                job.error = "Cancelled by user."
                job.finished_at = _now_iso()
                job.log.append("🛑 Cancelled by user")
                job.log.append("🧹 Cleaned up .offload/ directory")
            self._procs.pop(project_path, None)
        self._publish_event(project_path, "project.init.status", {"status": STATUS_FAILED, "error": "Cancelled by user."})
        return True

    def _publish_event(self, project_path: str, event_type: str, payload: Dict[str, Any]) -> None:
        if not self._event_bus:
            return
        from .models import EventRecord
        import uuid
        event = EventRecord(
            event_id=f"evt-{uuid.uuid4().hex[:12]}",
            event_type=event_type,
            payload={**payload, "project_path": project_path},
        )
        self._event_bus.publish(event)

    def trigger(self, project_path: str) -> bool:
        """
        Start an init job in the background for the given repo path.
        Returns True if started, False if one was already running.
        """
        with self._lock:
            existing = self._jobs.get(project_path)
            if existing and existing.status == STATUS_INITIALIZING:
                return False
            self._jobs[project_path] = _InitJob(
                project_path=project_path,
                status=STATUS_INITIALIZING,
                started_at=_now_iso(),
            )
        thread = threading.Thread(target=self._run, args=(project_path,), daemon=True)
        thread.start()
        return True

    def _run(self, project_path: str) -> None:
        repo = RepoOffload(Path(project_path))

        def append_log(msg: str) -> None:
            with self._lock:
                job = self._jobs.get(project_path)
                if job is None:
                    return
                job.log.append(msg)
                if len(job.log) > MAX_LOG_LINES:
                    del job.log[: len(job.log) - MAX_LOG_LINES]
            self._publish_event(project_path, "project.init.log", {"line": msg})

        try:
            append_log("📦 Staging .offload/init/ template…")
            repo.stage_init_template()
            append_log("📝 Ensuring .gitignore contains .offload/")
            repo.ensure_gitignore()
            repo.update_state(
                init_started_at=_now_iso(),
                init_template_version=1,
            )
            def register_proc(proc: subprocess.Popen) -> None:
                with self._lock:
                    self._procs[project_path] = proc

            result = repo.run_claude_init(log_callback=append_log, register_proc=register_proc)

            with self._lock:
                self._procs.pop(project_path, None)
                # If cancel() already set status to failed, respect that
                job = self._jobs.get(project_path)
                if job and job.status == STATUS_FAILED and job.error == "Cancelled by user.":
                    return

            if result.success:
                repo.update_state(
                    init_finished_at=_now_iso(),
                    init_status=STATUS_READY,
                )
                with self._lock:
                    job = self._jobs.get(project_path)
                    if job:
                        job.status = STATUS_READY
                        job.finished_at = _now_iso()
                self._publish_event(project_path, "project.init.status", {"status": STATUS_READY})
            else:
                repo.update_state(
                    init_finished_at=_now_iso(),
                    init_status=STATUS_FAILED,
                    init_error=result.error,
                )
                with self._lock:
                    job = self._jobs.get(project_path)
                    if job:
                        job.status = STATUS_FAILED
                        job.finished_at = _now_iso()
                        job.error = result.error
                self._publish_event(project_path, "project.init.status", {"status": STATUS_FAILED, "error": result.error})
        except Exception as e:  # noqa: BLE001 — top-level safety
            with self._lock:
                job = self._jobs.get(project_path)
                if job:
                    job.status = STATUS_FAILED
                    job.finished_at = _now_iso()
                    job.error = f"Unexpected error: {e}"
            self._publish_event(project_path, "project.init.status", {"status": STATUS_FAILED, "error": str(e)})


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
